config/routes.rb
Rails.application.routes.draw do
  root to: 'recipes#index'
  resources :recipes, only: %i[index show destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  require 'net/http'

  def index
    uri = URI('http://localhost:3000/api/v1/recipes')
    res = Net::HTTP.get(uri)
    @recipes = JSON.parse(res)
  end

  def show
    uri = URI("http://localhost:3000/api/v1/recipes/#{params[:id]}")
    res = Net::HTTP.get(uri)
    @recipe = JSON.parse(res)
    @recipe_type = set_recipe_type(@recipe['recipe_type_id'])
    @cuisine = set_cuisine(@recipe['cuisine_id'])
  end

  def destroy
    # uri = URI("http://localhost:3000/api/v1/recipes/"), params: { recipe: params[:id], user: 1 }
    # http = Net::HTTP.new(uri.host, uri.port)
    # req = Net::HTTP::Delete.new(uri.path)
    # res = http.request(req)

  end

  private

  def set_recipe_type(parameter)
    uri = URI("http://localhost:3000/api/v1/recipe_types/#{parameter}")
    recipe_type = Net::HTTP.get(uri)
  end

  def set_cuisine(parameter)
    uri = URI("http://localhost:3000/api/v1/cuisines/#{parameter}")
    cuisine = Net::HTTP.get(uri)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MirrorApi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <ul class="navbar-nav">
      <li class="nav-item active">
        <%= link_to t(:all_recipes), root_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to t(:create_recipes), root_path, class: 'nav-link' %>
      </li>
    </ul>
    </nav>
    <div class="bg-info text-center">
      <h1 class="text-white">Recipes Mirror</h1>
      <small class="text-white">O mirror que cai junto com o server xD</small>
    </div>
    <hr>
    <div class="container">
      <%= yield %>
    </div>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

app/views/recipes/index.html.erb
<%#= @recipes %>
<div class="row float-left ml-0 mr-1">
    <% @recipes.each do |recipe| %>
      <div class="col-md-7">
      <div class="card mb-4 shadow-sm">
        <div class="card-body">
          <h1 class="h4">
            <%= link_to recipe['title'], recipe_path(recipe['id']) %>
          </h1>
          <% if recipe['spotlight'] %>
            <%#= image_tag 'star.png', class:'spotlight'%>
            <p>Receita em destaque</p>
          <% end %>
          <ul>
            <li><%= recipe['difficulty'] %></li>
            <li><%= recipe['cook_time'] %> min</li>
          </ul>
        </div>
      </div>
      </div>
    <% end %>

app/views/recipes/show.html.erb
<div class="col-md-6">
<div class="card mb-4 shadow-sm">
  <div class="card-body">
    <h1 class="h4"><%= @recipe['title'] %></h1>
    <% if @recipe['spotlight'] %>
      <%#= image_tag 'star.png', class:'spotlight'%>
      <p>Receita em destaque</p>
    <% end %>
    <ul>
      <li>Tipo da receita</li>
      <li><%= @recipe_type['recipe_type'] %></li>
      <li>Cozinha</li>
      <li><%= @cuisine['cuisine'] %></li>
      <li>Dificuldade</li>
      <li><%= @recipe['difficulty'] %></li>
      <li>Tempo de preparo</li>
      <li><%= @recipe['cook_time'] %> min</li>
      <li>ingredientes</li>
      <li><%= @recipe['ingredients'] %></li>
      <li>Método de preparo</li>
      <li><%= @recipe['cook_method'] %></li>
      <li>Receita criada por</li>
      <li><%= @recipe['user_id'] %></li>
      <li>Data de criação</li>
      <li><%= @recipe['created_at'] %></li>
    </ul>
  </div>
</div>
</div>

<%= link_to t(:back), root_path, class: 'btn btn-primary' %>
<%= link_to t(:edit_recipes), root_path, class: 'btn btn-warning' %>
<%= link_to t(:delete_recipes), recipe_path, method: :delete, data: {confirm: 'Deseja apagar essa receita?'}, class: 'btn btn-danger' %>